# Generated by Django 5.2.10 on 2026-02-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('commercial_credit', 'Commercial Credit'), ('commercial_payment', 'Commercial Payment'), ('retail_credit', 'Retail Credit'), ('retail_payment', 'Retail Payment')], max_length=50, unique=True)),
                ('file', models.FileField(upload_to='bank_files/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
    ]
