# Generated by Django 5.2.10 on 2026-02-04 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_message', models.JSONField(blank=True, default=dict, help_text='Structured log of events/errors')),
                ('profiling_stats', models.JSONField(blank=True, default=dict, help_text='Performance breakdown (timers, row counts)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='orchestrator.syncjob')),
            ],
        ),
    ]
