# Generated by Django 5.2.11 on 2026-02-05 23:28

import orchestrator.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_syncreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncjob',
            name='loan_category',
            field=models.CharField(choices=[('COMMERCIAL', 'COMMERCIAL'), ('RETAIL', 'RETAIL')], default=orchestrator.constants.LoanCategory['COMMERCIAL'], max_length=20),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='remote_version_credit',
            field=models.IntegerField(blank=True, help_text='Version of credit file processed', null=True),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='remote_version_payment',
            field=models.IntegerField(blank=True, help_text='Version of payment file processed', null=True),
        ),
        migrations.AddField(
            model_name='syncreport',
            name='total_rows_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncreport',
            name='validation_errors',
            field=models.JSONField(default=list, help_text='List of validation failures (e.g. Missing Loan IDs)'),
        ),
        migrations.AlterField(
            model_name='syncreport',
            name='profiling_stats',
            field=models.JSONField(blank=True, default=dict, help_text='Performance breakdown, Data profiling metrics'),
        ),
    ]
